[package]
name = "xtask-art"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
image.workspace = true
reqwest.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true

[lib]
name = "xtask_art"
path = "src/lib.rs"

[[bin]]
name = "xtask-art"
path = "src/main.rs"

[[test]]
name = "unit"
path = "tests/unit/mod.rs"

[dev-dependencies]
image.workspace = true
tempfile = "3.27.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "test-util"] }
wiremock = "0.6.5"
