brew "gh"
brew "prek"
brew "rustup"
brew "cargo-nextest"
brew "uv"
# The Khronos glTF-Validator ships as an npm package, and there is no
# Homebrew formula for it. Bun installs and runs it.
brew "bun"
brew "lychee"
brew "git-lfs"
brew "bashunit"
brew "shellcheck"
brew "actionlint"
brew "cargo-deny"

cask "claude"
cask "claude-code@latest"
cask "visual-studio-code"
cask "blender"
cask "google-chrome"
cask "godot"
