brew "gh"
brew "prek"
brew "rustup"
brew "cargo-nextest"
brew "uv"
brew "lychee"
brew "git-lfs"
brew "bashunit"
brew "shellcheck"
brew "actionlint"
brew "cargo-deny"

cask "claude"
cask "claude-code@latest"
cask "visual-studio-code"
cask "blender"
cask "godot"
