[package]
name = "render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
game.workspace = true
worldgen.workspace = true
host.workspace = true
godot.workspace = true
sprites.workspace = true

[lints]
workspace = true

[[test]]
name = "unit"
path = "tests/unit/mod.rs"
