[package]
name = "worldgen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[[test]]
name = "unit"
path = "tests/unit/mod.rs"

[dependencies]
csv = { workspace = true }
fastnoise-lite = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
