// Test binary: `unwrap()` is the idiomatic assertion here, and a panic is the
// failure report. The workspace forbids it in real code, where a panic is a
// crash.
#![allow(clippy::unwrap_used)]

mod clips;
mod concepts;
mod frames;
mod gltf_bytes;
mod meshes;
mod rigs;
mod stubs;
mod support;
mod test_aim;
mod test_atlas;
mod test_bake;
mod test_bake_stage;
mod test_blender;
mod test_check;
mod test_cli;
mod test_cli_commands;
mod test_cli_concept;
mod test_cli_fetch;
mod test_cli_prompts;
mod test_cli_run;
mod test_clip;
mod test_concept;
mod test_conform;
mod test_foot;
mod test_gltf_mesh;
mod test_gltf_world;
mod test_http;
mod test_library;
mod test_lock;
mod test_mesh;
mod test_meshy;
mod test_meshy_client;
mod test_mixamo;
mod test_mixamo_client;
mod test_mixamo_session;
mod test_openai;
mod test_openai_client;
mod test_pack;
mod test_pack_stage;
mod test_preview;
mod test_profile;
mod test_providers;
mod test_rig;
mod test_spec;
mod test_spike;
mod test_stages;
mod test_stages_run;
mod test_validator;
